//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.ServiceLoginBolitaReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MVCBolitaServices.Servicio")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLoginBolitaReference.IServiceLogin")]
    public interface IServiceLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/GetData", ReplyAction="http://tempuri.org/IServiceLogin/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/GetData", ReplyAction="http://tempuri.org/IServiceLogin/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/ValidateCredentials", ReplyAction="http://tempuri.org/IServiceLogin/ValidateCredentialsResponse")]
        bool ValidateCredentials(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/ValidateCredentials", ReplyAction="http://tempuri.org/IServiceLogin/ValidateCredentialsResponse")]
        System.Threading.Tasks.Task<bool> ValidateCredentialsAsync(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/ValidateConnection", ReplyAction="http://tempuri.org/IServiceLogin/ValidateConnectionResponse")]
        string ValidateConnection(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/ValidateConnection", ReplyAction="http://tempuri.org/IServiceLogin/ValidateConnectionResponse")]
        System.Threading.Tasks.Task<string> ValidateConnectionAsync(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/ValidateCredentialsNuevo", ReplyAction="http://tempuri.org/IServiceLogin/ValidateCredentialsNuevoResponse")]
        bool ValidateCredentialsNuevo(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/ValidateCredentialsNuevo", ReplyAction="http://tempuri.org/IServiceLogin/ValidateCredentialsNuevoResponse")]
        System.Threading.Tasks.Task<bool> ValidateCredentialsNuevoAsync(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceLogin/GetDataUsingDataContractResponse")]
        MVCProject.ServiceLoginBolitaReference.CompositeType GetDataUsingDataContract(MVCProject.ServiceLoginBolitaReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogin/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceLogin/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MVCProject.ServiceLoginBolitaReference.CompositeType> GetDataUsingDataContractAsync(MVCProject.ServiceLoginBolitaReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLoginChannel : MVCProject.ServiceLoginBolitaReference.IServiceLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLoginClient : System.ServiceModel.ClientBase<MVCProject.ServiceLoginBolitaReference.IServiceLogin>, MVCProject.ServiceLoginBolitaReference.IServiceLogin {
        
        public ServiceLoginClient() {
        }
        
        public ServiceLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public bool ValidateCredentials(string user, string password) {
            return base.Channel.ValidateCredentials(user, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCredentialsAsync(string user, string password) {
            return base.Channel.ValidateCredentialsAsync(user, password);
        }
        
        public string ValidateConnection(int n) {
            return base.Channel.ValidateConnection(n);
        }
        
        public System.Threading.Tasks.Task<string> ValidateConnectionAsync(int n) {
            return base.Channel.ValidateConnectionAsync(n);
        }
        
        public bool ValidateCredentialsNuevo(string user, string password) {
            return base.Channel.ValidateCredentialsNuevo(user, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCredentialsNuevoAsync(string user, string password) {
            return base.Channel.ValidateCredentialsNuevoAsync(user, password);
        }
        
        public MVCProject.ServiceLoginBolitaReference.CompositeType GetDataUsingDataContract(MVCProject.ServiceLoginBolitaReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MVCProject.ServiceLoginBolitaReference.CompositeType> GetDataUsingDataContractAsync(MVCProject.ServiceLoginBolitaReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
